### ISSUE TITLE
sfpowerkit plugin stop working with sf cli versions newer than 2.34.7 (i.e. right after switch from yarn to npm installer was introduced)

### ISSUE THREAD

**Issue by avesolovksyy** [forcedotcom/cli#2849]
### Summary
We've tried to switch our CI pipelines to use latest sf cli version (currently we are using sf cli **2.34.7**, the one that is still using yarn, not npm installer). But we noticed that sfpowerkit plugin doesn't work with sf cli > 2.34.7.
In particular, plugin installation has succeeded, but subsequent execution of any command fails with error MODULE_NOT_FOUND.

### Steps To Reproduce
```
# installing sfpowerkit plugin: success, no errors as such
sf plugins install --force sfpowerkit@$latest
```

```
# trying to call some sfpowerkit command, like log in to org by creds => results in error
sf sfpowerkit:auth:login -a targetOrg -u "${TARGET_ORG_USERNAME}" -p "${TARGET_ORG_PASSWORD}" -r "${TARGET_ORG_URL}" --json
```

### Expected result
User has successfully logged into the org.

### Actual result
The following error is thrown:
```
 ›   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load /home/vsts/.loc
 ›   al/share/sf/node_modules/sfpowerkit/lib/commands/sfpowerkit/auth/login.js:
 ›    Cannot find module 'rimraf'
 ›   Require stack:
 ›   - /home/vsts/.local/share/sf/node_modules/sfpowerkit/lib/commands/sfpowerk
 ›   it/auth/login.js
 ›   - /usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib
 ›   /module-loader.js
 ›   - /usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib
 ›   /help/index.js
 ›   - /usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib
 ›   /errors/handle.js
 ›   - /usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib
 ›   /errors/index.js
 ›   - /usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib
 ›   /cli-ux/index.js
 ›   - /usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib
 ›   /index.js
 ›   Code: MODULE_NOT_FOUND
```

### System Information

```json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.38.7",
  "nodeVersion": "node-v18.20.2",
  "osVersion": "Linux 6.5.0-1018-azure",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.15 (core)",
    "@oclif/plugin-commands 3.3.1 (core)",
    "@oclif/plugin-help 6.0.21 (core)",
    "@oclif/plugin-not-found 3.1.4 (core)",
    "@oclif/plugin-plugins 5.0.10 (core)",
    "@oclif/plugin-search 1.0.22 (core)",
    "@oclif/plugin-update 4.2.6 (core)",
    "@oclif/plugin-version 2.0.17 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.38.7 (core)",
    "apex 3.1.5 (core)",
    "auth 3.6.1 (core)",
    "data 3.3.1 (core)",
    "deploy-retrieve 3.6.3 (core)",
    "info 3.2.1 (core)",
    "limits 3.3.3 (core)",
    "marketplace 1.2.1 (core)",
    "org 4.1.1 (core)",
    "packaging 2.4.0 (core)",
    "schema 3.3.3 (core)",
    "settings 2.2.1 (core)",
    "sobject 1.3.3 (core)",
    "source 3.3.1 (core)",
    "telemetry 3.3.2 (core)",
    "templates 56.2.2 (core)",
    "trust 3.6.3 (core)",
    "user 3.5.2 (core)",
    "sfpowerkit 6.1.0 (user)"
  ]
}
```
### Additional information
After digging a bit dipper, we've noticed that after sfpowerkit plugin installation, there is no dependencies available in **node_modules** folder:

`ls -la /home/vsts/.local/share/sf/node_modules`

```
total 192
drwxr-xr-x 3 vsts docker   4096 Apr 18 22:13 .
drwxr-xr-x 3 vsts docker   4096 Apr 18 22:13 ..
-rw-r--r-- 1 vsts docker 180532 Apr 18 22:13 .package-lock.json
drwxr-xr-x 6 vsts docker   4096 Apr 18 22:13 sfpowerkit
```

So seems like 'rimraf' module is just happen to be the first one that is imported in sfpowerkit code base, but the error is not specific to this module, i.e. any other module along execution path would trigger the same error.

Such behaviour is observed only if sf cli version is **> 2.34.7**
For older version (**<= 2.34.7**) node_modules directory is full of dependencies right after sfpowerkit plugin installation, and no errors observerd when using sfpowerkit commands further.

**Comment by mshanemc** [comment]
This is a bug in `sfpowerkit` (a mistake in their dependencies).

They are using `rimraf` here in "real" code https://github.com/dxatscale/sfpowerkit/blob/main/src/commands/sfpowerkit/auth/login.ts

but they don't include it in their dependencies (only in dev-dependencies) 
https://github.com/dxatscale/sfpowerkit/blob/4600d2fb783edffb52d9a4ecc915b0499c6dcc77/package.json#L74

It worked previously because *something* else somewhere in the CLI was including the same version of `rimraf` that powerkit was using in its **regular, non-dev** dependencies.  But that's just a MODULE_NOT_FOUND waiting to happen when the other package changes its dependencies.

---
 
it's probably worth noting that the creators of sfpowerkit have archived and deprecated the project.
https://github.com/dxatscale/sfpowerkit and want you to use a different plugin.

This lint rule prevents that mistake: https://github.com/forcedotcom/eslint-config-salesforce-typescript/blob/6e20ebdb2cca41eb8b2ae42950f08912237fd1ad/index.js#L99
