### ISSUE TITLE
force:org:delete:  this.org.getSandboxOrgConfigField is not a function

### ISSUE THREAD

**Issue by ashwini-raman** [forcedotcom/cli#176]
When running the sfdx force:org:delete -u TARGETUSERNAME, I get the following error:
**ERROR running force:org:delete:  this.org.getSandboxOrgConfigField is not a function**

This command used to work earlier, but it started throwing this error a few days back. Updated sfdx CLI version, but that didnt help.

I am on _sfdx-cli/7.22.0-de5c6ecff8 darwin-x64 node-v10.15.3_ version

**Comment by baksale** [comment]
Are you sure it tries to delete scratch org and not a sandbox?
Please check force:org:list

**Comment by ashwini-raman** [comment]
I am trying to delete a scratch org.

**Comment by VicccccW** [comment]
same issue here, I tried both force:org:delete -u <alias> and force:org:delete -u <xxx@xxxx>, same error.
I am trying to delete a Scratch org, not sandbox

**Comment by douglascayers** [comment]
I also had this issue when I was on version 7.22. After updating to 7.23 the issue was resolved for me.

For those still reporting the issue, see if [updating](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm) your CLI and/or [reinstalling](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm) the CLI fixes the issue for you.

```
$ sfdx --version
sfdx-cli/7.23.1-ced0ec4940 darwin-x64 node-v10.15.3
```

**Comment by ashwini-raman** [comment]
updating the CLI didnt work for me. Reinstalling the CLI fixed it though. 
Thanks
