### ISSUE TITLE
sfdx force:source:retrieve -x manifest/package.xml crashing after upgrade to v7.170 : versions.map is not a function

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/cli#1730]
### Summary

Command `sfdx force:source:retrieve -x manifest/package.xml` crashes since I upgraded to sfdx v7.170

### Steps To Reproduce:

1.  I log in to my customer's production org
1.  sfdx force:source:retrieve -x manifest/package.xml

### Expected result

Should retrieve the Salesforce metadata

### Actual result

```
% sfdx force:source:retrieve -x manifest/package.xml                       
ERROR running force:source:retrieve:  versions.map is not a function
Preparing retrieve request... done
```
### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.) : zsh
```
% sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.170.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@mshanemc/plugin-streaming 1.1.7 (user)",
    "@mshanemc/sfdx-sosl 1.1.0 (user)",
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "@salesforce/lwc-dev-server 2.11.0 (user)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.8 (core)",
    "community 2.0.1 (core)",
    "config 1.4.20 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.1.3 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.3 (core)",
    "packaging 1.9.1 (core)",
    "schema 2.1.6 (core)",
    "signups 1.2.2 (core)",
    "source 2.0.15 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.4 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.1 (core)",
    "sfdmu 4.16.10 (user)",
    "sfdx-xxx-plugin 0.0.2 (link) /Users/rupert/xxx/sfdx-xxx-plugin",
    "sfpowerkit 5.0.0 (user)",
    "shane-sfdx-plugins 4.43.0 (user)"
  ],
  "osVersion": "Darwin 20.6.0",
  "shell": "zsh",
  "rootPath": "/Users/rupert/.local/share/sfdx/client/7.170.0-bd51991"
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by cristiand391** [comment]
Hey @AltiusRupert, I think this is a dup of https://github.com/forcedotcom/cli/issues/1687

If you set the apiVersion with `sfdx config:set apiVersion=55.0` or `SFDX_API_VERSION=50.0 sfdx ...` do you get the same error?

**Comment by RupertBarrow** [comment]
OK, I've checked the other issue : same problem, your workaound works, I saw the issue was being fixed by Shane.
Thanks.

**Comment by RupertBarrow** [comment]
You may close this issue @cristiand391
